build-job:
  stage: build
  environment: production
  artifacts:
    paths:
      - ".next"
      - "node_modules"
      - "ecosystem.config.js"
      - "package.json"
    when: always
  before_script:
    - npm ci
  script:
    - npm run build

deploy-pm2-job:
  stage: deploy
  environment: production
  dependencies:
    - build-job
  variables:
    NEXT_BASE_API_URL: http://192.168.0.19:8000
    NEXT_STATIC_SERVER_URL: http://192.168.0.19:9000
  script: 
    - mkdir -p /var/www/recipe/frontend
    - rm -rf /var/www/recipe/frontend/*
    - mv .next node_modules ecosystem.config.js package.json /var/www/recipe/frontend
    - cd /var/www/recipe/frontend
    - pm2 startOrRestart ecosystem.config.js
