build-job:
  stage: build
  environment: production
  artifacts:
    paths:
      - "dist"
      - "node_modules"
      - "ecosystem.config.js"
    when: always
  before_script:
    - npm ci
  script:
    - npm run build
    - npm run seed:prod:run

deploy-pm2-job:
  stage: deploy
  environment: production
  dependencies:
    - build-job
  variables:
    NEXT_BASE_API_URL: http://192.168.0.19:8000
    NEXT_STATIC_SERVER_URL: http://192.168.0.19:9000
  script: 
    - mkdir -p /var/www/recipe/server
    - rm -rf /var/www/recipe/server/*
    - mv dist/* /var/www/recipe/server
    - mv node_modules /var/www/recipe/server
    - mv ecosystem.config.js /var/www/recipe/server
    - cd /var/www/recipe/server
    - pm2 startOrRestart ecosystem.config.js
