stages:
  - deploy

deploy:
  tags:
    - production
  variables:
    NEXT_BASE_API_URL: http://192.168.0.19:8000
    NEXT_STATIC_SERVER_URL: http://192.168.0.19:9000
  stage: deploy
  script: ./build.sh
  environment: production
