services:
  frontend:
    image: recipes-frontend:latest
    container_name: recipes-frontend
    environment:
      HOSTNAME:
      PORT: ${PORT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_SERVER_URL:
        NEXT_PUBLIC_STATIC_SERVER_URL:
      no_cache: true
    ports:
      - ${PORT}:3000
    restart: unless-stopped
